var languages_list = {
    uzbek_lt:"O'zbek",
    uzbek_cyr:"Ўзбек",
}
var languages = {
    uzbek_lt: {
        apptitle:"Kosonsoydagi eng yirik internet bozor",
        introduction_first_heading:"Kun talabi",
        introduction_second_heading:"Unikal yechimlar",
        introduction_third_heading:"Siz uchun maxsus",
        introduction_first_paragraph:"XXI asrda sizning biznesingiz internetda yo’qmi, demak siz biznesda yo’qsiz. Kelajakni biz bilan quring, sizni qo'llab quvvatlashga doimo tayyormiz.",
        introduction_second_paragraph:"Davr talablariga monand ish olib borish: Biz har bir mijoz takliflariga alohida yondashamiz.",
        introduction_third_paragraph:"Hamjihatlik maqsadlar sari eltadi. Biz sizga muvaffaqiyatlar sirini ochishga tayyormiz.",
        select_custom_language:"Iltimoz o'zingizga qulay bo'lgan tilni tanlang",
        copyright:" &copy; Copyright 2019 <a href=\"/aboutapp\">DEVCON P/E</a><br />Powered by Manuchehr Usmonov.",
        emailortelegram:"E-pochta yoki telegram manzil",
        phonenumber:"Telefon raqam",
        fullname:"To'liq ism",
        address:"Manzil",
        fieldssubtitle:"Tizimdan to'laqonli foydalanish uchun iltimos kerakli maydonlarni to'ldiring",
        continue:"Davom etish",
        fieldsempty:"Maydonlar to'ldirilmadi!",
        search:"Izlash",
        instructionsPullToRefresh:"Yangilash uchun pastga torting",
        instructionsReleaseToRefresh: "Yangilash uchun qo'yib yuboring",
        instructionsRefreshing: "Yangilanmoqda",
        postad:"E'LON JOYLASH",
        postad_small:"E'lon joylash",
        menu:"Menyu",
        ads:"E'lonlar",
        news:"Xabarlar",
        bookmarks:"Xatcho'plar",
        aboutus:"Biz haqimizda",
        settings:"Sozlamalar",
        aboutapp:"Dastur haqida",
        specialads:"Maxsus e'lonlar",
        simpleads:"Oddiy e'lonlar",
        moreads:"dan ortiq e'lonlar",
        filter:"Ma'lumotlarni saralash",
        filter_selectprice:"Narxni belgilash",
        filter_category:"Bo'lim",
        filter_no_results_text:"Ma'lumotlar topilmadi",
        filter_select:"Tanlash",
        filter_button:"Saralash",
        connectionerror:"Serverga ulanishda xatolik. Qurilmangizda internet yoqilganligiga ishonch hosil qiling!",
        all_items:"Barchasi",
        bookmark_added:"Xatcho'p saqlandi",
        bookmark_removed:"Xatcho'p o'chirildi",
        bookmarks_removed:"Xatcho'plar o'chirildi",
        loading_content:"Yuklanmoqda",
        please_wait:"Iltimos kuting...",
        error:"Xatolik",
        notfound:"So'rovingizga binoan hech qanday ma'lumot topilmadi...",
        covenant: "kelishilgan",
        share_with: "Ulashish",
        link: "Havola",
        do_you_have_delete_all_bookmarks: "Siz rostdan ham barcha xatcho'plarni o'chirmoqchimisiz?",
        yes:"Ha",
        no:"Yo'q",
        categories:"Ruknlar",
        contact: "Aloqa",
        contactinfo: "Aloqa ma'lumotlari",
        subject: "Mavzu",
        message: "Xabar",
        send:"Yuborish",
        close:"Yopish",
        about_project: "Kosonsoymarket haqida",
        adversitement: "Reklama xizmati",
        allads:"Umumiy e'lonlar",
        activeads:"Faol e'lonlar",
        allusers:"Foydalanuvchilar",
        dailyusers:"Kuzatuvchilar",
        paid_services:"Pullik xizmatlar",
        paid_services_title:"Endi sizning eʼloningiz uchun qaysi xizmat yaxshiroq natija berishi haqida oʻylab oʻtirishingizga xojat yoʻq. Faqatgina uni qay darajada koʻzga tashlanadigan qilish va qanchalar tezroq bitim tuzish istagida ekaningiz toʻgʻrisida qaror qabul qilsangiz bas!",
        partners: "Hamkorlarimiz",
        message_send_successfull: "Xabar muvaffaqiyatli yuborildi!",
        message_send_error: "Xabarni yuborishda xatolik!",
        aboutapp_version: "Dastur versiyasi",
        aboutapp_version_value: "1.0.1",
        aboutapp_lisension: "Litsenziya",
        aboutapp_lisension_value: "Bepul",
        aboutapp_release: "Ishlab chiqarilgan sana",
        aboutapp_release_value: "15.11.2019",
        aboutapp_author: "Ishlab chiqaruvchi",
        aboutapp_author_value: "DEVCON P/E",
        aboutapp_developer: "Dasturchi",
        aboutapp_developer_value: "Manuchehr Usmonov",
        aboutapp_website: "Web sayt",
        aboutapp_website_value: "www.devcon.uz",
        aboutapp_contact: "Aloqa ma'lumotlari",
        aboutapp_contact_value: "+99891 180-50-15, support@devcon.uz",
        settings_language:"Ilova tili",
        settings_list_item:"E'lonlar ko'rinishi",
        settings_notifications:"Bildirishnomalar",
        settings_vibration:"Vibroto'lqin",
        settings_audio:"Musiqiy bildirishnoma",
        settings_nightmode:"Tungi rejim",
        settings_trafic:"Trafikni tejash",
        settings_user_info:"Shaxsiy ma'lumotlar",
        settings_save:"Saqlash",
        rules:"Foydalanish shartlari",
        postad_title:"Sarlavha",
        postad_category:"Rukn",
        postad_price:"Narx",
        postad_currency:"Valyuta",
        postad_covenant:"Kelishuv",
        postad_covenant_0:"Odatiy",
        postad_covenant_1:"Kelishilgan",
        postad_content:"Tasnif",
        postad_pricing:"Xizmat turi",
        dropify_default:"Fotosurat tanlash",
        dropify_replace:"Fotosuratni yangilash",
        dropify_remove:"Tozalash",
        dropify_error:"Harakatni amalga oshirishda xatolik yuzberdi",
        post_added:"E'lon muvaffaqiyatli yuborildi!"
    },
    uzbek_cyr: {
        apptitle:"Косонсойдаги энг йирик интернет бозор",
        introduction_first_heading:"Кун талаби",
        introduction_second_heading:"Уникал ечимлар",
        introduction_third_heading:"Сиз учун махсус",
        introduction_first_paragraph:"XXI асрда сизнинг бизнесингиз интернетда йўқми, демак сиз бизнесда йўқсиз. Келажакни биз билан қуринг, сизни қўллаб қувватлашга доимо тайёрмиз.",
        introduction_second_paragraph:"Давр талабларига монанд иш олиб бориш: Биз ҳар бир мижоз таклифларига алоҳида ёндашамиз.",
        introduction_third_paragraph:"Ҳамжиҳатлик мақсадлар сари элтади. Биз сизга муваффақиятлар сирини очишга тайёрмиз.",
        select_custom_language:"Илтимоз ўзингизга қулай бўлган тилни танланг",
        copyright:" &copy; Copyright 2019 <a href=\"/aboutapp\">DEVCON P/E</a><br />Powered by Manuchehr Usmonov.",
        emailortelegram:"Э-почта ёки телеграм манзил",
        phonenumber:"Телефон рақам",
        fullname:"Тўлиқ исм",
        address:"Манзил",
        fieldssubtitle:"Тизимдан тўлақонли фойдаланиш учун илтимос керакли майдонларни тўлдиринг",
        continue:"Давом этиш",
        fieldsempty:"Майдонлар тўлдирилмади!",
        search:"Излаш",
        instructionsPullToRefresh:"Янгилаш учун пастга тортинг",
        instructionsReleaseToRefresh: "Янгилаш учун қўйиб юборинг",
        instructionsRefreshing: "Янгиланмоқда",
        postad:"ЭЪЛОН ЖОЙЛАШ",
        postad_small:"Эълон жойлаш",
        menu:"Меню",
        ads:"Эълонлар",
        news:"Хабарлар",
        bookmarks:"Хатчўплар",
        aboutus:"Биз ҳақимизда",
        settings:"Созламалар",
        aboutapp:"Дастур ҳақида",
        specialads:"Махсус эълонлар",
        simpleads:"Оддий эълонлар",
        moreads:"дан ортиқ эълонлар",
        filter:"Маълумотларни саралаш",
        filter_selectprice:"Нархни белгилаш",
        filter_category:"Бўлим",
        filter_no_results_text:"Маълумотлар топилмади",
        filter_select:"Танлаш",
        filter_button:"Саралаш",
        connectionerror:"Серверга уланишда хатолик. Қурилмангизда интернет ёқилганлигига ишонч ҳосил қилинг!",
        all_items:"Барчаси",
        bookmark_added:"Хатчўп сақланди",
        bookmark_removed:"Хатчўп ўчирилди",
        bookmarks_removed:"Хатчўплар ўчирилди",
        loading_content:"Юкланмоқда",
        please_wait:"Илтимос кутинг...",
        error:"Хатолик",
        notfound:"Сўровингизга биноан ҳеч қандай маълумот топилмади...",
        covenant: "Келишилган",
        share_with: "Улашиш",
        link: "Ҳавола",
        do_you_have_delete_all_bookmarks: "Сиз ростдан ҳам барча ҳатчўпларни ўчирмоқчимисиз?",
        yes:"Ҳа",
        no:"Йўқ",
        categories:"Бўлимлар",
        contact: "Алоқа",
        contactinfo: "Алоқа маълумотлари",
        subject: "Мавзу",
        message: "Хабар",
        send:"Юбориш",
        close:"Ёпиш",
        about_project: "Косонсоймаркет ҳақида",
        adversitement: "Реклама хизмати",
        allads:"Умумий эълонлар",
        activeads:"Фаол эълонлар",
        allusers:"Фойдаланувчилар",
        dailyusers:"Кузатувчилар",
        paid_services:"Пуллик хизматлар",
        paid_services_title:"Энди сизнинг эълонингиз учун қайси хизмат яхшироқ натижа бериши ҳақида оʻйлаб оʻтиришингизга хожат йўқ. Фақатгина уни қай даражада кўзга ташланадиган қилиш ва қанчалар тезроқ битим тузиш истагида эканингиз тўғрисида қарор қабул қилсангиз бас!",
        partners: "Ҳамкорларимиз",
        message_send_successfull: "Хабар муваффақиятли юборилди!",
        message_send_error: "Хабарни юборишда хатолик!",
        aboutapp_version: "Дастур версияси",
        aboutapp_version_value: "1.0.1",
        aboutapp_lisension: "Лицензия",
        aboutapp_lisension_value: "Бепул",
        aboutapp_release: "Ишлаб чиқарилган сана",
        aboutapp_release_value: "15.11.2019",
        aboutapp_author: "Ишлаб чиқарувчи",
        aboutapp_author_value: "DEVCON P/E",
        aboutapp_developer: "Дастурчи",
        aboutapp_developer_value: "Манучеҳр Усмонов",
        aboutapp_website: "Веб сайт",
        aboutapp_website_value: "www.devcon.uz",
        aboutapp_contact: "Алоқа маълумотлари",
        aboutapp_contact_value: "+99891 180-50-15, support@devcon.uz",
        settings_language:"Илова тили",
        settings_list_item:"Эълонлар кўриниши",
        settings_notifications:"Билдиришномалар",
        settings_vibration:"Вибротўлқин",
        settings_audio:"Мусиқий билдиришнома",
        settings_nightmode:"Тунги режим",
        settings_trafic:"Трафикни тежаш",
        settings_user_info:"Шахсий маълумотлар",
        settings_save:"Сақлаш",
        postad_pricing:"Хизмат тури",
        rules:"Фойдаланиш шартлари",
        postad_title:"Сарлавҳа",
        postad_category:"Рукн",
        postad_price:"Нарх",
        postad_currency:"Валюта",
        postad_covenant:"Келишув",
        postad_covenant_0:"Одатий",
        postad_covenant_1:"Келишилган",
        postad_content:"Тасниф",
        dropify_default:"Фотосурат танлаш",
        dropify_replace:"Фотосуратни янгилаш",
        dropify_remove:"Тозалаш",
        dropify_error:"Ҳаракатни амалга оширишда хатолик юзберди",
        post_added:"Элон муваффақиятли юборилди!"
    }

};
/*var p = [ 645,629,648 ];
var start = 648;
var next = p[($.inArray(start, p) + 1) % p.length];
var prev = p[($.inArray(start, p) - 1 + p.length) % p.length];

console.log(next);
console.log(prev);*/